PATHS:
  # This file is used to extract the locations (and other metadata) of the discovered GRGs
  # It is only used if ANNOTATE_POSITIVES is True, to link the known GRG positions to the cutouts for annotation.
  GIANTS_CATALOG_FILEPATH: "/home/penchev/strw_lofar_data_utils/data/GGO_catalogue_2025_11.csv"

  # This file is used to link components to sources for the annotation procedure
  COMPONENT_CATALOGUE_FILEPATH: "/net/vdesk/data2/penchev/project_data/data/combined_cat/combined-components-v0.8.fits"

  # Where to save the generated dataset
  SAVE_DIR: "/net/vdesk/data2/penchev/project_data/search-dataset/"

MOSAICS_TO_CRAWL:
  # Total cutouts in top 25 mosaics: 327
  MOSAICS_NAME: ['P217+35', 'P219+32', 'P216+32', 'P152+32', 'P220+35', 'P122+49', 'P145+32', 'P201+30', 'P124+32', 'P132+37', 'P132+42', 'P144+35', 'P158+32', 'P167+40', 'P169+55', 'P174+42', 'P177+37', 'P181+42', 'P184+42', 'P206+37', 'P216+37', 'P219+52', 'P228+30', 'P252+38', 'P112+37']
  STRIDE: 0.5 # 0.5 stride means 50% overlap between cutouts
  ANNOTATE_POSITIVES: True # Whether to annotate the cutouts that contain known GRGs from the catalog

CUTOUT_PARAMS:
  CUTOUT_SIZE: 300 # pixels - this gives us 300 pixels after rotation of 45 degrees
  RMS: 0.0001
  NR_SIGMAS: 3 # Number of sigmas above RMS to consider for source segmentation

AUGMENTATION:
  # to keep consistency with previous work by Moesterd et al.
  # It is possible to use 'asinh_stretch' as well
  STRETCH_TYPE: "sqrt_stretch"
  
  # Limits the number of islands to precompute per cutout.
  # This limits the number of precomputed proposals we get for the RCNN model.
  # The number of proposals is equal to 2^n - 1, where n is the number of islands.
  MAX_PRECOMPUTED_ISLANDS: 10

  # "rle" or "polygon" - how to represent the segmentation masks for annotation.
  # RLE is more compact, while polygon can be more interpretable for annotators.
  # This is only relevant if ANNOTATE_POSITIVES is True, as it determines how
  # the known GRG positions are annotated in the cutouts.
  SEGMENTATION_MODE: "rle"

PIPELINE:
  WORKERS: 10 # Number of parallel workers to use for dataset building
