"""Frozen preprocessing function **v1** for the Euclid Q1 BYOL dataset.

DO NOT EDIT THIS FILE once any dataset has been generated with it.

Every image that is ever fed to a model trained on this dataset (pretraining,
fine-tuning, evaluation, future test images) must go through exactly this code.
Any change -- a constant, the order of operations, even a docstring -- changes
:data:`FINGERPRINT` (SHA-256 of this file), and the pipeline refuses to mix
files with different fingerprints. To change the preprocessing, copy this file
to ``preprocess_v2.py``, bump :data:`VERSION`, and regenerate the dataset. The
regression test ``tests/projects/euclid_byol/test_preprocess_v1.py`` pins the
exact output bytes of a synthetic image, so an accidental change (including a
behaviour change in a numpy/astropy upgrade) fails loudly.

Input: a cutout of a Euclid MER **background-subtracted** VIS mosaic
(``EUC_MER_BGSUB-MOSAIC-VIS``), in mosaic units, at the native 0.1"/px.

Steps
-----
1. **Geometry** (:func:`extract_cutout`): a ``OUTPUT_SIZE`` x ``OUTPUT_SIZE``
   pixel window around the nearest pixel to the source position, with the
   source at pixel ``(OUTPUT_SIZE // 2, OUTPUT_SIZE // 2)``. No resampling.
   Pixels outside the mosaic are NaN.
2. **Blank pixels**: non-finite pixels and exact zeros (no mosaic coverage)
   are set to 0, the background level of the background-subtracted mosaic.
3. **Noise** (per image): ``sigma`` = sigma-clipped MAD standard deviation of
   the non-blank pixels. No local background is subtracted: the mosaic is
   already background-subtracted, and a local median would remove light from
   galaxies that fill the cutout.
4. **Asinh stretch and normalisation**, with ``astropy.visualization``::

       vmin = -VMIN_NSIGMA * sigma          (just below the noise floor)
       vmax = max(image)                    (min-max: brightest pixel -> 1)
       a    = ASINH_A_NSIGMA * sigma / (vmax - vmin)
       y    = ImageNormalize(vmin, vmax, AsinhStretch(a), clip=True)(image)

   The stretch is linear within about ``ASINH_A_NSIGMA`` sigma of ``vmin``
   (keeps the noise texture and faint outskirts) and logarithmic above
   (compresses bright cores without saturating them; only the brightest
   pixel maps to 1). The lower bound is fixed in noise units, not the image
   minimum, so a pixel value means the same signal-to-noise in every image.
5. **Quantisation**: ``round(255 * y)`` as ``uint8``.

Parameters are per image (noise-adaptive ``a``), fixed as the constants below.
"""
from __future__ import annotations

import hashlib
import io
import os
from pathlib import Path
from typing import Any, Dict, Optional, Tuple, Union

import numpy as np
from astropy.io import fits
from astropy.stats import sigma_clipped_stats
from astropy.visualization import AsinhStretch, ImageNormalize
from astropy.wcs import WCS
from astropy.wcs.utils import proj_plane_pixel_scales

VERSION = "v1"

#: Output side length in pixels (Zoobot's training resolution).
OUTPUT_SIZE = 224
#: Native MER VIS mosaic pixel scale; inputs at another scale are rejected.
EXPECTED_PIXEL_SCALE_ARCSEC = 0.1
PIXEL_SCALE_RTOL = 0.01
#: Sigma clipping used for the noise estimate.
NOISE_SIGMA_CLIP = 3.0
NOISE_MAXITERS = 5
#: Lower bound of the normalisation, in units of the noise below zero.
VMIN_NSIGMA = 2.0
#: Asinh softening parameter in units of the noise.
ASINH_A_NSIGMA = 3.0

#: SHA-256 of this file; stored with every generated image.
FINGERPRINT = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()


def extract_cutout(data: np.ndarray, wcs: WCS, ra: float, dec: float, size: int = OUTPUT_SIZE) -> np.ndarray:
    """Cut a ``size`` x ``size`` window centred on the pixel nearest to (ra, dec).

    The source lands on pixel ``(size // 2, size // 2)`` (row, column).
    Parts of the window outside ``data`` are NaN.

    :param data: 2D image.
    :param wcs: Celestial WCS of ``data``.
    :param ra: Right ascension in degrees (ICRS).
    :param dec: Declination in degrees (ICRS).
    :param size: Output side length in pixels.
    :return: float64 array of shape ``(size, size)``.
    """
    x, y = wcs.world_to_pixel_values(ra, dec)
    cx, cy = int(np.floor(float(x) + 0.5)), int(np.floor(float(y) + 0.5))
    x0, y0 = cx - size // 2, cy - size // 2
    out = np.full((size, size), np.nan, dtype=np.float64)
    ny, nx = data.shape
    sx0, sy0 = max(x0, 0), max(y0, 0)
    sx1, sy1 = min(x0 + size, nx), min(y0 + size, ny)
    if sx1 > sx0 and sy1 > sy0:
        out[sy0 - y0:sy1 - y0, sx0 - x0:sx1 - x0] = data[sy0:sy1, sx0:sx1]
    return out


def preprocess_with_stats(image: np.ndarray) -> Tuple[np.ndarray, Dict[str, Any]]:
    """Apply the v1 preprocessing and return the image with diagnostics.

    :param image: 2D cutout in mosaic units (see module docstring).
    :return: ``(uint8 image, stats)``. ``stats`` has ``noise_sigma``, ``vmin``,
        ``vmax``, ``asinh_a``, ``blank_fraction`` and ``degenerate``. A
        degenerate image (no valid pixels, or zero noise) is all zeros.
    """
    x = np.array(image, dtype=np.float64)
    if x.ndim != 2:
        raise ValueError(f"Expected a 2D image, got shape {x.shape}.")
    blank = ~np.isfinite(x) | (x == 0)
    x[blank] = 0.0
    stats: Dict[str, Any] = {
        "noise_sigma": np.nan, "vmin": np.nan, "vmax": np.nan, "asinh_a": np.nan,
        "blank_fraction": float(blank.mean()), "degenerate": True,
    }
    valid = x[~blank]
    if valid.size < 16:
        return np.zeros(x.shape, dtype=np.uint8), stats

    _, _, sigma = sigma_clipped_stats(
        valid, sigma=NOISE_SIGMA_CLIP, maxiters=NOISE_MAXITERS, cenfunc="median", stdfunc="mad_std"
    )
    vmin = -VMIN_NSIGMA * sigma
    vmax = float(x.max())
    if not (np.isfinite(sigma) and sigma > 0 and vmax > vmin):
        return np.zeros(x.shape, dtype=np.uint8), stats

    a = ASINH_A_NSIGMA * sigma / (vmax - vmin)
    norm = ImageNormalize(vmin=vmin, vmax=vmax, stretch=AsinhStretch(a=a), clip=True)
    y = np.ma.getdata(norm(x)).astype(np.float64)
    out = np.round(np.clip(y, 0.0, 1.0) * 255.0).astype(np.uint8)
    stats.update(noise_sigma=float(sigma), vmin=float(vmin), vmax=vmax, asinh_a=float(a), degenerate=False)
    return out, stats


def preprocess(image: np.ndarray) -> np.ndarray:
    """Apply the v1 preprocessing: raw cutout -> uint8 image.

    :param image: 2D cutout in mosaic units.
    :return: uint8 array of the same shape.
    """
    return preprocess_with_stats(image)[0]


def read_image_hdu(source: Union[bytes, str, os.PathLike]) -> Tuple[np.ndarray, WCS]:
    """Read the first 2D image HDU of a FITS file (path or raw bytes).

    :raises ValueError: If there is no 2D image or the pixel scale is not the
        native VIS scale.
    """
    handle = io.BytesIO(source) if isinstance(source, (bytes, bytearray)) else source
    with fits.open(handle, memmap=False) as hdul:
        hdu = next((h for h in hdul if h.data is not None and np.ndim(h.data) == 2), None)
        if hdu is None:
            raise ValueError("No 2D image HDU found.")
        data = np.asarray(hdu.data, dtype=np.float64)
        wcs = WCS(hdu.header).celestial
    scale = float(np.mean(proj_plane_pixel_scales(wcs))) * 3600.0
    if not np.isclose(scale, EXPECTED_PIXEL_SCALE_ARCSEC, rtol=PIXEL_SCALE_RTOL):
        raise ValueError(
            f"Pixel scale {scale:.4f}\"/px differs from the expected {EXPECTED_PIXEL_SCALE_ARCSEC}\"/px."
        )
    return data, wcs


def preprocess_fits(
    source: Union[bytes, str, os.PathLike],
    ra: Optional[float] = None,
    dec: Optional[float] = None,
) -> Tuple[np.ndarray, np.ndarray, Dict[str, Any]]:
    """Cut out and preprocess a source from a FITS image (path or raw bytes).

    :param source: FITS file path or bytes (e.g. a cutout-service response).
    :param ra: Source RA in degrees; with ``dec`` ``None``, the image centre is used.
    :param dec: Source Dec in degrees.
    :return: ``(uint8 image, raw float32 cutout, stats)``.
    """
    data, wcs = read_image_hdu(source)
    if ra is None or dec is None:
        ny, nx = data.shape
        ra, dec = wcs.pixel_to_world_values((nx - 1) / 2.0, (ny - 1) / 2.0)
    raw = extract_cutout(data, wcs, float(ra), float(dec))
    image, stats = preprocess_with_stats(raw)
    return image, raw.astype(np.float32), stats
