PATHS:
  # This file is used to extract the locations (and other metadata) of the discovered GRGs
  GIANTS_CATALOG_FILEPATH: "/home/penchev/strw_lofar_data_utils/data/GGO_catalogue_2025_11.csv"

  # RGZ-specific
  RGZ_RADEC_LIST_FILEPATH: "/home/penchev/strw_lofar_data_utils/data/rgz_sources_coords.csv"

  # This file is used to link components to sources for the annotation procedure
  COMPONENT_CATALOGUE_FILEPATH: "/net/vdesk/data2/penchev/catalogues/combined-components-v1.1.fits"

  # Where to save the generated dataset
  SAVE_DIR: "/net/vdesk/data2/penchev/project_data/rgz_full_dataset"
  
CUTOUT_PARAMS:
  CUTOUT_SIZE: 425 # pixels - this gives us 300 pixels after rotation of 45 degrees
  CROP_SIZE: 300 # pixels - final size after rotation and cropping
  RMS: 0.0001
  NR_SIGMAS: 3 # Number of sigmas above RMS to consider for source segmentation

AUGMENTATION:
  # to keep consistency with previous work by Moesterd et al.
  # It is possible to use 'asinh_stretch' as well
  STRETCH_TYPE: "sqrt_stretch"

  # Angles in degrees to rotate the cutouts for data augmentation. 0 means no rotation.
  ROTATION_ANGLES: [0, 45, 90, 135, 180]
  
  # Limits the number of islands to precompute per cutout.
  # This limits the number of precomputed proposals we get for the RCNN model.
  # The number of proposals is equal to 2^n - 1, where n is the number of islands.
  MAX_PRECOMPUTED_ISLANDS: 10

  CLASS_RATIO: 0 # Ratio of negative to positive samples (e.g., 1 means equal number of negatives and positives)

ANNOTATIONS:
  MULTICLASS: true # Whether to use multiclass annotations
  INVALID_LABEL: 0 # Label for invalid samples (e.g., proposals without sources)
  SCS_LABEL: 1 # Label for SCS class (if multiclass is true)
  MCS_LABEL: 2 # Label for MCS class (if multiclass is true)

PIPELINE:
  WORKERS: 10 # Number of parallel workers to use for dataset building
  LIMIT_RADEC_LIST: null # null # Limit the number of RA/DEC positions to process (for testing) - leave null to process all
  LIMIT_CUTOUTS: null # null # Limit the number of cutouts to process (for testing) - leave null to process all
  